# Generated by Django 3.2.9 on 2021-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('fld_slno', models.AutoField(primary_key=True, serialize=False)),
                ('fld_rn', models.IntegerField()),
                ('fld_rf_id', models.IntegerField()),
                ('fld_full_name', models.CharField(max_length=100)),
                ('fld_i_identify_as_id', models.IntegerField()),
                ('fld_i_identify_as_name', models.CharField(max_length=100)),
                ('fld_age', models.CharField(max_length=100)),
                ('fld_country_of_residence', models.CharField(max_length=100)),
                ('fld_email', models.CharField(max_length=100)),
                ('fld_telephone_number', models.CharField(max_length=100)),
                ('fld_tuberculosis_id', models.IntegerField()),
                ('fld_tuberculosis_name', models.CharField(max_length=100)),
                ('fld_am_person_id', models.IntegerField()),
                ('fld_am_person_name', models.CharField(max_length=100)),
                ('fld_organizational_affiliations', models.CharField(max_length=100)),
                ('fld_working_with_TB_HIV', models.CharField(max_length=100)),
                ('fld_part_of_this_training', models.CharField(max_length=100)),
                ('fld_is_active', models.IntegerField(default=1)),
                ('fld_sys_inserted_datetime', models.DateTimeField(auto_now_add=True)),
                ('fld_modified_no', models.CharField(max_length=100)),
                ('fld_modified_datetime', models.CharField(max_length=100)),
                ('fld_is_deleted', models.CharField(default='', max_length=100)),
                ('fld_reason_for_delete', models.CharField(max_length=100)),
                ('fld_deleted_datetime', models.CharField(default='', max_length=100)),
                ('fld_logged_in_user_id', models.CharField(max_length=100)),
                ('fld_data_source', models.CharField(max_length=100)),
                ('fld_form_start_time', models.CharField(max_length=100)),
                ('fld_form_end_time', models.CharField(max_length=100)),
                ('fld_is_eligeble_to_login', models.CharField(max_length=100)),
            ],
        ),
    ]
