# Generated by Django 3.2.9 on 2021-11-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCTA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='fld_is_eligeble_to_login',
        ),
    ]
