# Generated by Django 3.2.9 on 2021-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCTA', '0002_remove_registration_fld_is_eligeble_to_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='fld_is_eligeble_to_login',
            field=models.CharField(default='', max_length=100),
        ),
    ]
